name: "Test WorkFlows"
run-name: ${{github.actor}} is testing out github actions

on:
  push:
    branches:
      - main

jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The Job was automatically triggered by a ${{github.event_name}} event"
      - run: echo "This task is running on a ${{runner.os}} server hosted by Github!"
      - run: echo "The name of the your branch is ${{github.ref}} and your repository is ${{github.repository}}"

      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The repository has been cloned to the runner"

      - run: echo "The workflow is now ready to test your code on this runner"
      - name: List files in the repository
        run: ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
